### PR TITLE
Update deps and expand test suite

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Update simple-schema and eventemitter version rangers.
Do the same for mocha in testing and experiment with adding more versions for testing.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Honestly we should drop support for Meteor 1 series.

**Comment by harryadel** [comment]
@StorytellerCZ Fine by me, drop them

**Review by harryadel — APPROVED** [review]

**Comment by harryadel** [comment]
@StorytellerCZ :+1:

**Comment by jankapunkt** [comment]
The 1.x tests take ages....

**Comment by StorytellerCZ** [comment]
@jankapunkt it looks like they won't run the client tests.

**Pull request merged**
