### PR TITLE
Lazy module export

### PR DESCRIPTION
**Pull request by CaptainN**
Make module export lazy as per #394

### CODE REVIEW

**Comment by aldeed** [comment]
I guess this would be worth it, though I don't know why Meteor does it this way. It would be better if each project could just choose to depend on it lazily without requiring a breaking change to the package like this.

**Comment by CaptainN** [comment]
I agree. Meteor needs more of a peer dependency definition. This is probably a breaking change though - it would require some use cases do an intentional import. Maybe that's too much? IDK.

**Comment by aldeed** [comment]
I am transferring this to @Meteor-Community-Packages so I will let others help decide whether this is worth a major version release.

**Comment by StorytellerCZ** [comment]
I'm in agreement for major version update with this. Preferably with other changes updates like #250 so that there is a bit more goodies in the update.

**Comment by harryadelb** [comment]
Thank you @StorytellerCZ. I was kinda skeptical whether to do a major or minor update, as for including #250 it seems that needs more work so I'm unsure about it.

**Comment by StorytellerCZ** [comment]
@harryadelb Yes, but that is out of scope for this PR. It is just matter of including things and timing the release. Anyhow @CaptainN could you please update your PR to fix the conflicts and do a major version bump. Thanks!

**Comment by CaptainN** [comment]
I actually think this would be too difficult for most users. We should probably not merge this.

**Comment by copleykj** [comment]
@CaptainN why would this be difficult?

**Comment by CaptainN** [comment]
Users could have to intentionally import the package before creating their collections. It would not auto attach to the collections the way it does now.

**Comment by copleykj** [comment]
What about either exporting Collection after it's modified so that it makes sense as to why you are importing something, or a combination of that and make use of the technique outlined by this article by @jankapunkt: https://dev.to/jankapunkt/lightweight-meteor-packages-with-conditional-dynamic-imports-1d51 so that it's optional?

**Comment by CaptainN** [comment]
I like the idea of exporting the modified collection (collection2) instead of modifying the original the way it does now. That's a better pattern in general, IMHO. It would allow for better code splitting and all that too. 

But that's a HUGE change, and we'd need some wide discussion to catch any possible consequences that we aren't seeing. I generally support this idea though.

**Comment by StorytellerCZ** [comment]
@CaptainN I'm all for it. Maybe start a topic on the forums?

**Pull request closed without merging**
