### PR TITLE
add load function to lazy export minimal package code

### PR DESCRIPTION
**Pull request by jankapunkt**
**Table of Contents**  *generated with [DocToc](https://github.com/thlorenz/doctoc)*

- [What](#what)
- [Why](#why)

## What

Implemented a function `Collection2.load` that uses a nested import to load all the required functionality. The default export consists only of the EventEmitter instance.

## Why

see #394

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Don't forget to update readme. I think this will require major version bump.

**Comment by jankapunkt** [comment]
Yes this will be breaking IMO. I did not edited in the README anything yet, because I first wanted to know what you and @CaptainN think about this :-)

**Comment by harryadel** [comment]
Sorry for being late @jankapunkt but I'm willing to move forward with this. It's ok to introduce a major version update with new lazy load feature but can we also preserve static load type of way? Same way it was done in [autoform](https://github.com/Meteor-Community-Packages/meteor-autoform#import-using-static-imports) where they can statically import the package?

**Comment by jankapunkt** [comment]
@StorytellerCZ if we have a breaking release with Meteor 2.6, wouldn't it be a good chance to add this now and make a breaking 4.0 release?

**Comment by jankapunkt** [comment]
@StorytellerCZ @harryadel just getting back at this one. Would this have a chance to be merged when I resolve the conflicts?

**Comment by jankapunkt** [comment]
@StorytellerCZ @harryadel I created a new `release-4.0` branch and changed it to be the new base branch

**Comment by harryadel** [comment]
I had hoped we can merge this with the ability to import things statically like [autoform](https://github.com/Meteor-Community-Packages/meteor-autoform#import-using-static-imports).

**Comment by StorytellerCZ** [comment]
Let's play with this on the v4 branch.

**Comment by jankapunkt** [comment]
It should work both dynamic and static.

**Pull request merged**
