### PR TITLE
keep native errors for umanaged collections

### PR DESCRIPTION
**Pull request by DmytroSoninLinguahouse**
**Table of Contents**  *generated with [DocToc](https://github.com/thlorenz/doctoc)*

- [What](#what)
- [Why](#why)

## What
Change method monkey patching code to allow to return unaltered error message when collection isn't being validated and doesn't have any simplschema attached.

## Why
collection2 monkey patches Collection class globally changing collection instances for the whole project even if they don't use collection2 functionalities. 
For new collections we were using mongodb's native json schema validation, but errors returned by mongo are getting changed by collection2 and end up being unhelpful (it leaves the text message but strips any actual useful data from mongo error). 
This pr makes presence of collection2 less intrusive for collections that don't use collection2 for validation

### CODE REVIEW

**Comment by harryadel** [comment]
The change itself is alright but 1) Why did you change the entire package setup? 2) Can you please add testing for your changes?

**Comment by DmytroSoninLinguahouse** [comment]
@harryadel oh, my bad. Second commit wasn't meant for pr, it was for my fork only

**Comment by harryadel** [comment]
if the current tests suit passes and you add a test case for you change then I'll gladly accept it :)

**Comment by harryadel** [comment]
Thank you @DmytroSoninLinguahouse I'm adding the tests and continuing the work here
https://github.com/Meteor-Community-Packages/meteor-collection2/pull/460

**Comment by varofon** [comment]
@harryadel much appreciated. I had issues with running meteor locally for tests, I planned to make a dockerfile for it, but couldn't find time for it

**Pull request closed without merging**
