### PR TITLE
Remove clean options

### PR DESCRIPTION
**Pull request by harryadel**
https://github.com/Meteor-Community-Packages/meteor-collection2/pull/434#issuecomment-915454437

### CODE REVIEW

**Comment by copleykj** [comment]
Doing a quick search for `cleanoptions` in VS Code turns up quite a few references. If we are going to remove this, it should be done cleanly.

**Comment by harryadel** [comment]
Honestly, I hope we can bundle this PR with those two:
https://github.com/Meteor-Community-Packages/meteor-collection2/pull/430
https://github.com/Meteor-Community-Packages/meteor-collection2/issues/433 (still in discussion)

and do a major bump.

**Comment by copleykj** [comment]
Ok, I'm gonna try to pull everything down and have a thorough look tomorrow or Monday. It's been quite a while since I've had my head in this codebase.

**Comment by jankapunkt** [comment]
@harryadel can yougive me a short intro how to test this, so I can add a review?

**Comment by StorytellerCZ** [comment]
I've slated it for v4 as it is a potential breaking change.

**Comment by harryadel** [comment]
@StorytellerCZ It's ok to include it in v4 if you wish but it isn't breaking since the introduced feature wasn't working or adding any value so removing it won't cause any problems whatsoever.

**Comment by harryadel** [comment]
I'm going to merge it but no won't release anything yet until we decided on what else to include in v4.

**Comment by StorytellerCZ** [comment]
Sorry for getting to this so late. We should have gotten that into its own v4 branch for better visibility.

**Comment by harryadel** [comment]
We should also account for https://github.com/meteor/meteor/pull/12057 collection2 must work with async operations, no?

**Comment by StorytellerCZ** [comment]
Yes, that should be the major thing for v4

**Pull request merged**
