### PR TITLE
Fix #408

### LINKED ISSUE #408: Upsert no longer works in 3.0.5
The change done for #403 seems to break an existing upsert, that works in 3.0.4:

```javascript
Tags.upsert(
  { 
    "color": "orange", 
    "label": "Today", 
    "team": {
      "id": "jPrbLLC8mMQcMe6ZC",
      "slug": "myteam"
    }
  },
  {
    "$set": {
      "lastUsedAt": new Date
    }
  }
)
```

In 3.0.5 gives the following error: `Error: Team is required in tags update`

```
I20200107-20:20:52.143(1)?   invalidKeys: 
I20200107-20:20:52.144(1)?    [ { name: 'team', type: 'required', value: undefined },
I20200107-20:20:52.144(1)?      { name: 'team.id', type: 'required', value: undefined },
I20200107-20:20:52.144(1)?      { name: 'team.slug', type: 'required', value: undefined } ],
```

This is the schema:

```javascript
Tags.attachSchema(new SimpleSchema({
  team: {
    type: new SimpleSchema({
      id: {
        type: String
      },
      slug: {
        type: String
      }
    })
  },
  color: {
    type: String
  },
  label: {
    type: String
  },
  lastUsedAt: {
    type: Date
  }
}))
```

### PR DESCRIPTION
**Pull request by harryadelb**
Added `upsert vanilla nested objects which doesn't logical operators value` test case for #408

### CODE REVIEW

**Comment by harryadelb** [comment]
@SimonSimCity and @Rijk would you please guys give it a look?

**Comment by SimonSimCity** [comment]
So .... could you please revert your changes and split it up into a section of your actual changes and all the rest which is just related to some code-stylings? 😊

**Comment by harryadelb** [comment]
Yes, right away. Sorry!

**Comment by Rijk** [comment]
Wow, that was quick. Tested and confirmed it fixes the issue 💪

**Comment by SimonSimCity** [comment]
Yes, looks good 👍

**Comment by harryadelb** [comment]
Alright then, thank you guys!

**Comment by harryadelb** [comment]
@Rijk Please update your project. :)

**Comment by Rijk** [comment]
Thanks Harry!

**Comment by copleykj** [comment]
@harryadelb nice turn around time.

**Pull request merged**
